steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/clear-frame-ai-webpage:latest'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/clear-frame-ai-webpage:latest'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: /bin/sh
    args:
      - '-c'
      - |
        DB_USER=$(cat "$$DB_USER_SECRET")
        DB_PASS=$(cat "$$DB_PASS_SECRET")
        gcloud run deploy clear-frame-ai-webpage \
          --image=gcr.io/$PROJECT_ID/clear-frame-ai-webpage:latest \
          --region=us-west1 \
          --platform=managed \
          --allow-unauthenticated \
          --add-cloudsql-instances=$PROJECT_ID:us-west1:clear-frame-ai \
          --service-account=clear-frame-ai-wp@dev-portfolio-435323.iam.gserviceaccount.com \
          --set-env-vars=WORDPRESS_DB_HOST=/cloudsql/$PROJECT_ID:us-west1:clear-frame-ai,WORDPRESS_DB_NAME=wordpress,WORDPRESS_DB_USER=$DB_USER,WORDPRESS_DB_PASSWORD=$DB_PASS,WORDPRESS_DB_PORT=3306
    secretEnv:
      - DB_USER_SECRET
      - DB_PASS_SECRET

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/CFA-WP-DB-USER/versions/latest
      env: DB_USER_SECRET
    - versionName: projects/$PROJECT_ID/secrets/CFA-WP-DB-PASS/versions/latest
      env: DB_PASS_SECRET

images:
  - 'gcr.io/$PROJECT_ID/clear-frame-ai-webpage:latest'

options:
  logging: CLOUD_LOGGING_ONLY
