version: '3.8'

services:
  wordpress:
    image: wordpress:latest
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: ${CFA_WP_DB_HOST}
      WORDPRESS_DB_PORT: ${CFA_WP_DB_PORT}
      WORDPRESS_DB_USER: ${CFA_WP_DB_USER}
      WORDPRESS_DB_PASSWORD: ${CFA_WP_DB_PASS}
      WORDPRESS_DB_NAME: ${CFA_WP_DB_NAME}
    volumes:
      - ./wp-content:/var/www/html/wp-content
    depends_on:
      - cloudsqlproxy

  cloudsqlproxy:
    image: gcr.io/cloudsql-docker/gce-proxy:1.33.10
    command: >
      /cloud_sql_proxy
      -instances=dev-portfolio-435323:us-west1:clear-frame-ai=tcp:3306
      -credential_file=/secrets/dev-portfolio-435323-8b2b9c9a7009.json
    volumes:
      - ./secrets:/secrets:ro
    ports:
      - "3306:3306"
